--- 
title: "CDFW Introduction to R Programming"
author: "Liz Siemion"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
description: |
  CDFW Introduction to R Programming Workshop
link-citations: yes
github-repo: rstudio/bookdown-demo
---

# CDFW Introduction to R Programming {#overview}

## Overview

I reference course materials from USU's ecology center workshop, and Dr. Simona Picardi's  [Reproducible data science website](https://ecorepsci.github.io/reproducible-science/index.html). 

***

## Workshop Goals

This course is intended to teach the basic programming fundamentals of R and 
how to use RStudio. I hope to provide you with the skills needed to continue 
learning R on your own and to incorporate R into your analyses and workflows. 

***

## Workshop Content
1. [Into to R and R-Studio](#intro) <br> 
2. [Packages](#Packages) <br>
3. [File paths](#FilePaths) <br>
4. [Importing and exporting data files](#ImportExport) (csv, xlsx, mdb, rds)] <br>
5. [Working with R objects](#RObjects) <br>
6. [Data types](#DataTypes) (character, numeric, logical, etc.) and classes (scalar, vector, data frames, matrices, lists, etc.) <br>
7. [Functions](#Functions) (arguments, function workflow) <br>
8. [Data organization and manipulation](#DataOrg) (base R and tidyverse) <br>
9. [Indexing](#Index) <br>
10. [Basic plotting](#Plotting) <br>
11 [Basic statistics & statistical summaries](#Stats) <br>
12. [Introduction to debugging](#debugging) (how to ask the right questions) <br>
13. [Making readable R code](#ReadableR) (commenting, outlining, etc.)
